on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
name: Wiki Sync
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Sync Wiki
            uses: cmbrose/github-docs-to-wiki@master
            with:
                githubToken: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
                rootDocsFolder: docs
                useHeaderForWikiName: true
